{{- if .Values.mcpService.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pk-mcp.serviceAccountName" . }}
  namespace: {{ include "pk-mcp.namespace" . }}
  labels:
    {{- include "pk-mcp.mcpService.labels" . | nindent 4 }}
  {{- with .Values.mcpService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
