{{- if .Values.mcpService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pk-mcp.mcpService.fullname" . }}
  namespace: {{ include "pk-mcp.namespace" . }}
  labels:
    {{- include "pk-mcp.mcpService.labels" . | nindent 4 }}
  {{- with .Values.mcpService.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mcpService.service.type }}
  ports:
    - name: http
      port: {{ .Values.mcpService.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "pk-mcp.mcpService.selectorLabels" . | nindent 4 }}
{{- end }}
